export default [
    {
        title:'幻灯片管理',
        key:'banner',
        content:'',
        icon:'picture',
        children:[
            {
                title:'幻灯片列表',
                key:'banner-list',
                content:'Banner',
                children:[],
            },
            {
                title:'幻灯片添加',
                key:'banner-add',
                content:'Banner',
                children:[],
            }
        ],
    },
    {
        title:'新闻管理',
        key:'xinwenguanli',
        content:'',
        icon:'pie-chart',
        children:[
            {
                title:'新闻添加',
                key:'xinwenguanli-add',
                content:'',
                icon:'pie-chart',
                children:[],
            }
        ],
    },
    {
        title:'订单管理',
        key:'dingdanguanli',
        content:'',
        icon:'pie-chart',
        children:[],
    },
    {
        title:'材料管理',
        key:'cailiaoguanli',
        content:'',
        icon:'pie-chart',
        children:[],
    },
    {
        title:' 商品管理',
        key:'shangpinguanli',
        content:'',
        icon:'pie-chart',
        children:[],
    },
    {
        title:' 人员管理',
        key:'renyuanguanli',
        content:'',
        icon:'pie-chart',
        children:[],
    },
    {
        title:' 用户管理',
        key:'yonghuguanli',
        content:'',
        icon:'pie-chart',
        children:[],
    }
]